name: frontend
description: Client Inteface for Database Streamer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  mobx: 1.2.1+4
  flutter_mobx: 1.1.0+2
  rxdart: 0.25.0
  bot_toast: 3.0.5
  modal_progress_hud: 0.1.3
  google_fonts: 1.1.2
  font_awesome_flutter: 8.11.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: 1.11.5
  mobx_codegen: 1.1.2

flutter:
  uses-material-design: true
